# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - skype-bot-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Increase file descriptor limit
      run: |
        ulimit -n 4096
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: skype-bot-artifact
        path: D:\a\skype-bot-v2\skype-bot-v2\node_modules\send\node_modules\debug\src\
        maxConcurrency: 5

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: skype-bot-artifact
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6A6206657CEE40278229ABA127E9D487 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_399B2A6C896C4885BF5E3FE3569E7D3F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FB015E3050A24B5682940B787FC29395 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'skype-bot-app'
          slot-name: 'Production'
          package: .
          